#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no -p 61761 -i ~/vastai root@142.170.96.180 "sed -i 's/ProtectHome=read-only/ProtectHome=false/g' /etc/systemd/system/noland-state-agent.service && systemctl daemon-reload && systemctl restart noland-state-agent"
expect {
    "Enter passphrase for key" {
        send_user "SSH key is not loaded. Run: ssh-add ~/vastai\n"
        exit 1
    }
    eof
}
