[package]
name = "noland-pack"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
noland-cas.workspace = true
noland-crypto.workspace = true
noland-state-core.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
zstd.workspace = true
